export type StandingsList = Standing[]

export interface Standing {
  leagueId: string
  seasonId: string
  teamId: number
  teamCity: string
  teamName: string
  teamSlug: string
  conference: string
  conferenceRecord: string
  playoffRank: number
  clinchIndicator: string
  division: string
  divisionRecord: string
  divisionRank: number
  wins: number
  losses: number
  winPct: number
  leagueRank?: number
  record: string
  home: string
  road: string
  l10: string
  last10Home: string
  last10Road: string
  ot: string
  threePtsOrLess: string
  tenPtsOrMore: string
  longHomeStreak: number
  strLongHomeStreak: string
  longRoadStreak: number
  strLongRoadStreak: string
  longWinStreak: number
  longLossStreak: number
  currentHomeStreak: number
  strCurrentHomeStreak: string
  currentRoadStreak: number
  strCurrentRoadStreak: string
  currentStreak: number
  strCurrentStreak: string
  conferenceGamesBack: number
  divisionGamesBack: number
  clinchedConferenceTitle: number
  clinchedDivisionTitle: number
  clinchedPlayoffBirth: number
  clinchedPlayIn: number
  eliminatedConference: number
  eliminatedDivision: number
  aheadAtHalf: string
  behindAtHalf: string
  tiedAtHalf: string
  aheadAtThird: string
  behindAtThird: string
  tiedAtThird: string
  score100Pts: string
  oppScore100Pts: string
  oppOver500: string
  leadInFgpct: string
  leadInReb: string
  fewerTurnovers: string
  pointsPg: number
  oppPointsPg: number
  diffPointsPg: number
  vsEast: string
  vsAtlantic: string
  vsCentral: string
  vsSoutheast: string
  vsWest: string
  vsNorthwest: string
  vsPacific: string
  vsSouthwest: string
  jan: string
  feb: string
  mar: string
  apr: any
  may: any
  jun: any
  jul: any
  aug: any
  sep: any
  oct: string
  nov: string
  dec: string
  score80__Plus: string
  opp__Score80__Plus: string
  score__Below80: string
  opp__Score__Below80: string
  totalPoints: number
  oppTotalPoints: number
  diffTotalPoints: number
  leagueGamesBack: number
  playoffSeeding: any
  clinchedPostSeason: number
}
